from . import help
from . import start
from . import test_solution
from . import settings
from . import results
from . import referal
from . import admin
from . import activate_test
from . import de_activate_test
from . import add_test
from . import change_test
from . import echo
